# Generated by Django 6.0.1 on 2026-01-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='valor',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='duracao_minutos',
        ),
    ]
